language: node_js
sudo: false
node_js:
    - "0.10"
    - "0.12"
    - "4.4"
    - "6.2"
script:
    - npm test
    - npm run lint
branches:
    only:
        - master
cache:
    directories:
        - node_modules
